config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :user
  resources :city
  resources :gossips do
    resources :comments
  end
  
  
  get 'welcome/:name', to: 'welcome#home', as: 'welcome'
  get 'team/team'
  get 'contacts/contact'
  
  

  root 'gossips#index' 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name, presence: true
    validates :zip_code, presence: true

    has_many :users
    has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
 
  belongs_to  :gossip, optional: true
  belongs_to :user, optional: true
    

    
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    has_many :comments

    belongs_to :user, optional: true
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User", optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true
    validates :email, presence: true,  uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :age, presence: true, numericality: {only_integer: true}
    validates :password, presence: true
    
    

    belongs_to :city, optional: true
    has_many :gossips

    

    #has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    #has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def new
    @city = City.new(name: @ville)
  end

  def show
   @city = City.find(1)
   @gossips_city = City.find(1).gossips
   #puts @gossips_city
   #@city = City.find(params[:id])
   #@gossips_city = City.find(params[:id]).gossips
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  skip_before_action :verify_authenticity_token
  before_action :authenticate_user, only: [:create, :show, :new]
  before_action :authenticate_user_edit, only: [:edit, :update]

  def index
    @gossips = Gossip.all
    puts "ok"
    
  end

  def show
    @gossip = Gossip.find(params[:id])
    
  end
  
  def new
    @gossip = Gossip.new
  end
  
  def create
    @city = City.create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: @city)
    #@gossip = Gossip.create(gossip_params)
    @gossip.user = current_user
    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to root_path
    else
      render :new
    end
  end

  #def create
   # @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: 1) # avec xxx qui sont les données obtenues à partir du formulaire

    #if @gossip.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
     # puts "Tu as réussi "
      #redirect_to gossips_path
    #else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
     # puts "Ça ne fontionne pas"
      #render new_gossip_path
    #end
  
  #end
  

  def edit
    @gossip = Gossip.find(params[:id])          # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end


  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié
    @gossip = Gossip.find(params[:id])
    gossip_user = @gossip.user
    

    if @gossip.update(gossip_params)
      redirect_to gossips_path
      flash[:messages] = "Ton potin a été édité ! "
    else
      render edit_gossip_path
    end

  end


  def destroy
    puts "Methode trouvé"
    @gossip = Gossip.find(params[:id])
    @gossip.destroy if @gossip
    redirect_to gossips_path
    flash[:success] = "Ton potin a été supprimé "
    
  end


  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Connecte toi !"
      redirect_to new_session_path
    end
  end


end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def team
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end
 

  def show
    @user = User.find(params[:id])
  end

  def create
    @city = City.new
    
    #@user = User.new(users_params)
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: @city, password: params[:pass_first], password_confirmation: params[:pass_second])
    
    if @user.save
      puts "Je save l'utilisateur"
      log_in(@user)
      puts "Il est save"
      redirect_to gossips_path 
      flash[:success] = "Ton profil a été crée !"
    else
      puts "Redirige, pas save"
      render new_user_path
      flash[:danger] = "Remplissez tous les champs"
    end
  end

  private 

  def users_params  
    params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @name = params[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/session_helper.rb
module SessionHelper



end

app/helpers/sessions_helper.rb
module SessionsHelper


  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<center>
<div class="card user-card" style="width: 70%">
  <div class="card-body">
    <h5 class="card-title">Tu es sur la page de la ville de <%= @city.name %></h5>
    
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Zip code : <%= @city.zip_code %></li>
    
    </ul>
  </ul>
</div>
</center>

<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1>Bienvenue sur la page de la ville <%= @city.name %> </h1><br>
    </div>
  </div>

  

app/views/gossips/edit.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="card create-potin">
  <div class="card-header">
    <h2>Edition du potin:</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">

      <%= form_for(@gossip) do |f| %>
          <%= f.text_field :title, class: 'form-control' %>
          <br/>
          <%= f.text_area :content, class: 'form-control' %>
          <br/>
          <%= f.submit "Mettre à jour", class: 'btn btn-primary' %>
      <% end %>
    </blockquote>
  </div>
</div>

app/views/gossips/index.html.erb
<html>


<% if flash.any? %> 
  <% flash.each do |type, msg| %> 
    <div class="alert alert-<%= type %>"> 
    <%= msg %> 
    </div> 
  <% end %> 
<% end %>





  <head>
    <title> Gossip News </title>
  </head>

<body>
      <center>
  <div class="jumbotron"> 
    <div class="container">
      <div class=fond>
        <h1> Bienvenue ! Voici les potins de THP </h1> 
        <p> Vous retrouverez ici toute l'actualité des potins de THP, enjoy & bon comérage !</p>
        </br>
        </br>
        <p><a class="btn btn-primary btn-lg" href='<%= new_gossip_path %>' role="button"> Crée ton potin</a>
        </center>
      </div>
    </div>
  </div>
<center>
  <div class="row" style="width: 85%">
    <% puts @gossips %>
    <% @gossips.each do |gossip| %>
      <% if gossip.user %>
      <div class="col-sm-6">
        <div class="card" style="margin: 10px; padding: 25px 0 25px 0; border: 2.5px solid lightgrey; border-radius: 50px">
          <div class="card-header">
            <h3><%= gossip.title %></h3>
          </div>
          <div class="card-body">
            <h4><%= gossip.content %>
            <h5 class="card-title">A été écrit par <%= gossip.user.first_name  %></h5>
            <% end %>
            </br>
            <a class="btn btn-success" href="<%= gossip_path(gossip.id) %>">En savoir plus...</a>
            <%= link_to "Editer", edit_gossip_path(gossip.id), class:"btn btn-warning" %>
            </br>
            </br>
            <%= button_to "Supprimer", gossip, method: :delete, data: { confirm: "Tu es sur ?" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div> 
    <% end %>          
  </div> 
 
 </center>   
</body>
</html> 

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<center>
<div class="card create-potin">
  <div class="card-header">
    <h2>Création d'un potin</h2>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
      <%= label_tag 'Titre de ton potin' %><br>
      <%= text_field_tag 'title' %>
      <br>
      <%= label_tag 'Description de ton potin' %>
      <br/>
      <%= text_field_tag 'content' %>
      <br>
      <br/>
      <%= submit_tag 'Soumet ton potin', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
</center>

app/views/gossips/page.html.erb
<div class="card card-gossip">
  <div class="card-header">
    <H2><%= @gossip.title %></h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer">Cet article a été écrit par "<%= @gossip.user.first_name %> : <%= link_to "plus d'infos sur l'auteur", user_path(user: => @user.id) %>"</footer>
    </blockquote>
  </div>
</div>

app/views/gossips/show.html.erb
<center>
<div class="card" style="margin: 90px 250px; padding: 25px 0 25px 0; border: 1px solid lightgrey; border-radius: 30px">
  <div class="card-header text-center">
  <div class="panel panel-success class">
  <% if @gossip.user %>
        <div class="panel-heading">
          Cet article a été écrit par <b><%= @gossip.user.first_name %> : 
          <%= link_to "plus d'infos sur l'auteur", user_path() %></b>
        </div>
    </div>
    </div>
  

    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %></h5>
      <p class="card-text">"<%= @gossip.content %>"</p>
  <% end %>
  
    
    <%= link_to "Ecrire un commentaire", new_gossip_comment_path(@gossip.id) %>

  </div>
</div>



<div class="container">
  <div class="row bootstrap snippets bootdeys">
    <div>
      <div class="comment-wrapper">
        <div class="panel panel-info">
          <div class="panel-heading">
            Liste des commentaires 
          </div>
                
          <div class="panel-body">
            <div class="card my-1"> 
              <div class="card-body">

              
              

              </div>
            </div>
            <br>
            <br>

            <ul class="media-list"></ul>
              
                           
              
                       

            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<a class="btn btn-primary" href='<%= gossips_path %>'>Retour à l'acceuil</a>
</center>

app/views/user/new.html.erb
<% if flash.any? %> 
  <% flash.each do |type, msg| %> 
    <div class="alert alert-<%= type %>"> 
    <%= msg %> 
    </div> 
  <% end %> 
<% end %>



<center>
  <div class="card create-potin">
  <div class="card-header">
    <h2>Création d'un utilisateur</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <%= label_tag 'Nom' %>
        <br />
        <%= text_field_tag 'last_name' %>
        <br /> <br />

        <%= label_tag 'Prénom' %>
        <br />
        <%= text_field_tag 'first_name' %>
        <br /> <br />

        <%= label_tag 'Ville' %>
        <br />
        <%= text_field_tag '@ville' %>
        <br /> <br />

        <%= label_tag 'Une description de toi' %>
        <br />
        <%= text_area_tag 'description' %>
        <br /> <br />

        <%= label_tag 'E-mail' %>
        <br />
        <%= text_field_tag 'email' %>
        <br /> <br />

        <%= label_tag 'Age' %>
        <br />
        <%= text_field_tag 'age' %>
        <br /> <br />

        <%= label_tag 'Entre ton mot de passe' %>
        <br />
        <%= password_field_tag 'pass_first' %>
        <br /> <br />

        <%= label_tag 'Confirme ton mot de passe' %>
        <br />
        <%= password_field_tag 'pass_second' %>
        <br /> <br />

        <%= submit_tag "Créer mon profil", class: 'btn btn-primary' %>
      <% end %>
    </blockquote>
  </div>
</div>
</center>

app/views/user/show.html.erb
<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><strong><%= @user.last_name %> <%= @user.first_name %></strong></p></br>
        <img src="https://cdn.pixabay.com/photo/2017/02/25/22/04/user-icon-2098873_960_720.png" class="img-circle" height="65" width="65" alt="Avatar">
        </br></br>
        <p><strong>Contact</strong> : <%= @user.email %></p>
        <p><strong>Age</strong> : <%= @user.age %></p>
      </div>
      <div class="well">
        <p><strong>Intérêts</strong></p>
        <p>
          <span class="label label-default">THP</span>
          <span class="label label-primary">truestory</span>
          <span class="label label-success">Buzz</span>
          <span class="label label-info">TVreality</span>
          <span class="label label-warning">ChuckBoris</span>
          <span class="label label-danger">100Code</span>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Hey !</strong></p>
        Des gens ont visité ton profil !
      </div>
      <p><strong> Affiche tes liens içi :</strong></p>
      <p><a href="#">Monblogdecommere.tuconnais.viens</a></p>
      <p><a href="#">THPestmagique.pourquoi.pourquoipas</a></p>
      <p><a href="#">ChuckBoris.histoire.incroyable</a></p>
    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling Blue</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>     
            </div>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Auteur</p>
           
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Futur Potin</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Auteur</p>
           
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Futur Potin</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Auteur</p>
           
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Futur Potin</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Auteur</p>
           
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Futur Potin</p>
          </div>
        </div>
      </div>     
    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p><strong>Originaire de :</strong></p>
        
        <p><strong> <%= @user.city %> </strong></p>
        <%= link_to "Info", city_path(), class: "btn btn-primary" %> 
      </div>      
      <div class="well">
        <p></p>
      </div>
      <div class="well">
        <p></p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p></p>
</footer>

</body>
</html>