config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :user
  resources :city
  resources :gossips do
    resources :comments
  end
  
  
  get 'welcome/:name', to: 'welcome#home', as: 'welcome'
  get 'team/team'
  get 'contacts/contact'
  
  

  root 'gossips#index' 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name, presence: true
    validates :zip_code, presence: true

    has_many :users
    has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
 
  belongs_to  :gossip, optional: true
  belongs_to :user, optional: true
    

    
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    has_many :comments

    belongs_to :user, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User", optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true
    validates :email, presence: true,  uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    validates :age, presence: true, numericality: {only_integer: true}
    validates :password, presence: true
    
    

    belongs_to :city, optional: true
    has_many :gossips

    

    #has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    #has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def new
    @city = City.new(name: @ville)
  end

  def show
   @city = City.find(1)
   @gossips_city = City.find(1).gossips
   #puts @gossips_city
   #@city = City.find(params[:id])
   #@gossips_city = City.find(params[:id]).gossips
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def team
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end
 

  def show
    @user = User.find(params[:id])
  end

  def create
    @city = City.new
    
    #@user = User.new(users_params)
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], email: params[:email], age: params[:age], city_id: @city, password: params[:pass_first], password_confirmation: params[:pass_second])
    
    if @user.save
      puts "Je save l'utilisateur"
      log_in(@user)
      puts "Il est save"
      redirect_to gossips_path 
      flash[:success] = "Ton profil a été crée !"
    else
      puts "Redirige, pas save"
      render new_user_path
      flash[:danger] = "Remplissez tous les champs"
    end
  end

  private 

  def users_params  
    params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/session_helper.rb
module SessionHelper



end

app/helpers/sessions_helper.rb
module SessionsHelper


  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% if flash.any? %> 
  <% flash.each do |type, msg| %> 
    <div class="alert alert-<%= type %>"> 
    <%= msg %> 
    </div> 
  <% end %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>100 Code</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  
  
  </head>


  <body>
   <header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header"></div>
          <p class="navbar-brand">100Code</p>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", gossips_path, class: 'nav-link' %></li>
          <li><%= link_to "Team", team_team_path, class: 'nav-link' %></li>
          <li><%= link_to "Contacts", contacts_contact_path, class: 'nav-link' %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= button_to "Déconnexion", session_path(session.id), method: :delete, class: 'btn btn-danger', style: "margin: 10px" %></li>
            
          <% else %>
            <li><%= link_to "Créer ton compte", new_user_path, class: 'nav-link' %></li>
            <li><%= link_to "Se connecter", new_session_path, class: 'nav-link' %></li>
          <% end %>
        </ul>

      </div>
    </nav>




    

    <%= yield %>
   </header>
  </body>
</html>